image: Visual Studio 2019
configuration:
  - Debug
  - Release
platform:
  - x86
cache:
  # Cache Nuget packages in "packages" folder. Break cache if "packages.config" is updated.
  - packages -> **\packages.config
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
before_build: nuget restore
build:
  project: op2ext.sln
test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\test
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\test.exe'
  - cd %APPVEYOR_BUILD_FOLDER%\testDll
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\testDll.exe'
  - cd %APPVEYOR_BUILD_FOLDER%
after_build:
  # Set version/build tag
  - set Version=Build%APPVEYOR_BUILD_VERSION%
  - if defined APPVEYOR_REPO_TAG_NAME set Version=%APPVEYOR_REPO_TAG_NAME%
  # Set platform/configuration tag
  - set Config=%CONFIGURATION%
  - if defined PLATFORM set Config=%PLATFORM%-%Config%
  # Set overall build tag
  - set PackageBaseName="%APPVEYOR_PROJECT_NAME%-%Version%-%Config%"
  # Determine output folder
  - set OutputFolder=%APPVEYOR_BUILD_FOLDER%\%PLATFORM%\%CONFIGURATION%\
  - if not exist "%OutputFolder%" set OutputFolder=%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\
  # Package artifacts
  - 7z a "%PackageBaseName%.zip" "%OutputFolder%op2ext.dll"
  - 7z a "%PackageBaseName%-DebugSymbolPdb.zip" "%OutputFolder%op2ext.pdb"
artifacts:
  - path: "*.zip"
    name: BuildArtifacts
deploy:
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
    CONFIGURATION: Release
  artifact: BuildArtifacts
  description: ''
  provider: GitHub
  auth_token:
    secure: sNvqUedX6OZ4kgbx8OYUbqq3mSIg1Y8QCW+7w/piSSieaPZnK911w1JKpmQIXjPU
