image: Visual Studio 2017
configuration:
  - Debug
  - Release
platform:
  - x86
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
before_build: nuget restore
build:
  project: op2ext.sln
