version: 2
jobs:
  build:
    docker:
      - image: outpostuniverse/gcc-mingw-wine-googletest-circleci:1.2
    steps:
      - run: WINEARCH=win32 winecfg
      - checkout
      - run: git submodule update --init || true
      - run: make --keep-going --jobs=2 op2extLib
      - run: make --keep-going --jobs=2 op2extDll
      - run: make --keep-going --jobs=2 testLib
      - run: make --keep-going --jobs=2 testDll
      - run: make --keep-going --jobs=2 check-testLib
      - run: make --keep-going --jobs=2 check-testDll
