version: 2
jobs:
  build:
    docker:
      - image: outpostuniverse/gcc-mingw-wine-googletest-circleci:1.2
    steps:
      - run: WINEARCH=win32 winecfg
      - checkout
      - run: git submodule update --init || true
      - run: make --keep-going op2extLib
      - run: make --keep-going op2extDll
      - run: make --keep-going testLib
      - run: make --keep-going check-testLib
